[package]
name = "parallel_spawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.10"
serde = "1.0.152"
serde_derive = "1.0.152"

